import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import FeatureProducts from "@/sections/FeatureProducts";
import FeatureServices from "@/sections/FeatureServices";
import FeaturePosts from "@/sections/FeaturePosts";
import FeatureTestimonials from "@/sections/Testimonials";
import Footer from "@/components/Footer";
import Hometop from "@/sections/Hometop";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Hometop />

      <FeatureProducts />

      <FeatureServices />

      <FeaturePosts />

      <FeatureTestimonials />

      <Image
        alt="review"
        width={0}
        height={0}
        style={{ width: "100%", height: "100%" }}
        unoptimized
        src={"assets/banner-kitchen.png"}
      />

      <Footer />
    </>
  );
}
