import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import FeatureProducts from "@/screens/FeatureProducts";
import FeatureServices from "@/screens/FeatureServices";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />

      <div className="poster-homepage">
        <div>
          {" "}
          <Image
            alt="poster"
            width={0}
            height={0}
            style={{ width: "100%", height: "100%" }}
            unoptimized
            src={"assets/image-1.png"}
          />
        </div>
        <div className="d-flex flex-column ms-3">
          <Image
            alt="poster"
            width={0}
            height={0}
            style={{ width: "100%", height: "100%" }}
            unoptimized
            src={"assets/image-2.png"}
          />
          <div className="d-flex mt-3">
            <Image
              alt="poster"
              width={0}
              height={0}
              style={{ width: "100%", height: "100%" }}
              unoptimized
              src={"assets/image-3.png"}
            />{" "}
            <Image
              alt="poster"
              className="ms-3"
              width={0}
              height={0}
              style={{ width: "100%", height: "100%" }}
              unoptimized
              src={"assets/image-4.png"}
            />
          </div>
        </div>
      </div>

      <FeatureProducts />

      <FeatureServices />
    </>
  );
}
